language: node_js

node_js: stable

branches:
  only:
    - hexo

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_install:
  - git config --global user.name "wisfern"
  - git config --global user.email "wisfern@qq.com"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli
  - git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox

install:
  - yarn

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/wisfern/wisfern.github.io.git master

